-- 0014：「打开次数」入库（view_count）
--
-- 为什么改：此前打开次数是**纯本机**的 IndexedDB 计数（lib/client/views.ts），每台设备
-- 各算各的、也不随导出 / 导入往返。用户要求它**直接持久化进数据库**，并同步出现在导出
-- 的 JSON 与 CSV 里 —— 于是它从「本机数据」升格为「数据库字段」，也重新纳入字段台账。
--
-- 语义没有变：仍然是「**我自己**打开这一篇看过几次」，不是「被谁看过几次」。
-- 由 `POST /api/diary/[id]/view` 原子自增（`view_count = view_count + 1`），
-- 且**不碰 updated_at** —— 回看一篇不等于编辑，详情页不会因此冒出「编辑于」。
--
-- 默认 0 且 NOT NULL：历史行一律从 0 起算。
-- ★ 旧的**本机**计数刻意不迁移：它是按设备计的，把某一台设备的数字写进库，
--   等于把它冒充成全局真值（而且没有任何办法判断哪台更权威）。宁可全部从 0 开始。
ALTER TABLE "diary_entries" ADD COLUMN "view_count" integer DEFAULT 0 NOT NULL;
